name: base

on:
  workflow_dispatch:

jobs:
  send_repository_dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send repository_dispatch
        env:
          PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          curl -i -u molkree:$PAT https://api.github.com/users/molkree
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/molkree/github_actions/dispatches \
            -d '{"event_type":"base_built"}'
