name: Testing miniconda

on:
  workflow_dispatch:
  # schedule:
  #   # Runs every 7 minutes
  #   - cron: '*/7 * * * *'

jobs:
  testing_miniconda:
    runs-on: windows-latest

    steps:
      - uses: mamba-org/setup-micromamba@7f29b8b80078b1b601dfa018b0f7425c587c63bb # v2.0.6
        with:
          environment-name: pdftotext
          create-args: >-
            python=3.13
            poppler
            pdftotext
          cache-environment: true
      - name: Install pdftotext
        run: |
          conda install poppler pdftotext
