name: Testing miniconda

on:
  workflow_dispatch:
  # schedule:
  #   # Runs every 7 minutes
  #   - cron: '*/7 * * * *'

jobs:
  testing_miniconda:
    runs-on: windows-latest

    steps:
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase to reset cache
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}
      - uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3.2.0
        with:
          python-version: "3.13"
          auto-update-conda: true
          activate-environment: pdftotext
          use-only-tar-bz2: false # IMPORTANT: This needs to be set for caching to work properly!
          channels: conda-forge,defaults
      - name: Install pdftotext
        run: |
          conda install poppler pdftotext
