name: Base workflow

on:
  workflow_dispatch:

jobs:
  output_vars:
    runs-on: ubuntu-latest

    steps:
      - name: Set color
        id: random-color-generator
        run: |
          echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
          echo "selected_color=red" >> $GITHUB_OUTPUT
      - name: Get colors
        run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
          echo "The selected color is ${{ steps.random-color-generator.outputs.selected_color }}"
