name: Push to another repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'Molkree/LeetCode'
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Commit something
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --allow-empty -m "Empty commit"
          git push
